steps:

- name: gcr.io/cloud-builders/docker
  args: [ build, -t, gcr.io/$PROJECT_ID/gcp-cloudbuild-stack, gcptest/stockpred/Dockerfile ]

- name: gcr.io/cloud-builders/gcloud
  args: [ compute, instance-groups, managed, rolling-action, restart, <instance-group-name>, --zone=us-east1-b ]


images:

- gcr.io/$PROJECT_ID/gcp-cloudbuild-stack
